In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import os

df = pd.read_csv(os.path.join(os.getcwd(), 'house_price_dataset.csv'))

In [4]:
df.head(10)

,House_ID,Area_sqft,Bedrooms,Bathrooms,Floors,Year_Built,Location,Furnishing_Status,Parking_Available,Garage_Count,Lot_Size_sqft,Condition,Distance_to_City_Center_km,Crime_Rate_Index,School_Rating,Has_Pool,Renovated,Price
0,3975,1665.3,2.0,4.0,1.0,1988,Green field,Unfurnished,NO,3.0,4817.2,Excellent,4.23,51.48,6.36,No,no,309277.0
1,12325,2646.2,2.0,5.0,2.0,2005,riverside,NaN,no,3.0,6998.6,EXCELLENT,3.67,14.55,7.45,yes,Y,563512.0
2,7202,2791.2,4.0,3.0,3.0,2011,Lake side,Unfurnished,NO,0.0,3427.6,good,8.97,38.84,NaN,Yes,no,495806.0
3,8355,1594.1,2.0,3.0,1.0,1972,Hillview,semifurnished,no,3.0,5703.1,fair,1.54,38.31,1.60,no,Yes,240776.0
4,12742,3227.0,3.0,5.0,2.0,1995,NaN,Unfurnished,yes,3.0,7352.4,Good,5.06,30.50,4.72,no,yes,413975.0
5,4916,2281.8,1.0,3.0,1.0,1953,UPTOWN,Unfurnished,N,0.0,4966.8,EXCELLENT,10.71,46.14,5.95,no,no,326288.0
6,101,1897.5,3.0,4.0,2.0,2006,lakeside,semifurnished,YES,2.0,3032.8,fair,11.47,17.07,5.97,No,no,344460.0
7,5676,1793.5,5.0,1.0,2.0,1987,OldTown,semifurnished,no,0.0,4015.5,fair,0.20,31.92,NaN,no,No,259429.0
8,6876,2807.8,5.0,1.0,1.0,1953,River side,furnished,no,0.0,7387.7,Good,14.86,51.73,5.14,no,Yes,436933.0
9,8459,1307.1,3.0,3.0,2.0,2004,UPTOWN,UN-FURNISHED,YES,0.0,3155.7,EXCELLENT,28.44,36.44,7.12,N,yes,230813.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15025 entries, 0 to 15024
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   House_ID                    15025 non-null  int64
 1   Area_sqft                   14422 non-null  float64
 2   Bedrooms                    14575 non-null  float64
 3   Bathrooms                   14725 non-null  float64
 4   Floors                      15025 non-null  float64
 5   Year_Built                  15025 non-null  int64
 6   Location                    14274 non-null  object
 7   Furnishing_Status           14124 non-null  object
 8   Parking_Available           14422 non-null  object
 9   Garage_Count                14725 non-null  float64
 10  Lot_Size_sqft               14575 non-null  float64
 11  Condition                   14575 non-null  object
 12  Distance_to_City_Center_km  14725 non-null  float64
 13  Crime_Rate_Index            15025 non-null  float64
 14  School_Rating               13974 non-null  float64
 15  Has_Pool                    15025 non-null  object
 16  Renovated                   15025 non-null  object
 17  Price                       15025 non-null  float64
dtypes: float64(10), int64(2), object(6)
memory usage: 2.1+ MB

In [6]:
df.describe()

,House_ID,Area_sqft,Bedrooms,Bathrooms,Floors,Year_Built,Garage_Count,Lot_Size_sqft,Distance_to_City_Center_km,Crime_Rate_Index,School_Rating,Price
count,15025.000000,14422.000000,14575.000000,14725.000000,15025.000000,15025.000000,14725.000000,14575.000000,14725.000000,15025.000000,13974.000000,15025.000000
mean,7499.760532,2194.490639,3.509640,3.063837,1.729850,1986.528652,1.482784,5006.505818,8.067724,34.847353,6.461426,369062.817038
std,4330.190689,795.478584,1.722604,2.869786,0.661109,21.338712,1.119669,1982.719784,8.048765,14.922554,1.755776,127269.347523
min,1.000000,0.000000,-1.000000,1.000000,1.000000,1950.000000,0.000000,500.000000,0.200000,0.000000,1.000000,20000.000000
25%,3750.000000,1657.150000,2.000000,2.000000,1.000000,1968.000000,0.000000,3645.900000,2.320000,24.650000,5.270000,280791.000000
50%,7498.000000,2184.400000,4.000000,3.000000,2.000000,1987.000000,1.000000,4993.300000,5.610000,34.720000,6.480000,359454.000000
75%,11248.000000,2722.675000,5.000000,4.000000,2.000000,2005.000000,2.000000,6351.650000,11.180000,44.970000,7.700000,449125.000000
max,15000.000000,5521.000000,6.000000,99.000000,3.000000,2035.000000,3.000000,13370.800000,60.000000,100.000000,10.000000,926035.000000

In [8]:
df.shape

(15025, 18)

In [10]:
df.isnull().sum()

House_ID                         0
Area_sqft                      603
Bedrooms                       450
Bathrooms                      300
Floors                           0
Year_Built                       0
Location                       751
Furnishing_Status              901
Parking_Available              603
Garage_Count                   300
Lot_Size_sqft                  450
Condition                      450
Distance_to_City_Center_km     300
Crime_Rate_Index                 0
School_Rating                 1051
Has_Pool                         0
Renovated                        0
Price                            0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(25)

##Data Imputation

In [14]:
# Separate numerical and categorical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

In [15]:
num_cols

Index(['House_ID', 'Area_sqft', 'Bedrooms', 'Bathrooms', 'Floors',
       'Year_Built', 'Garage_Count', 'Lot_Size_sqft',
       'Distance_to_City_Center_km', 'Crime_Rate_Index', 'School_Rating',
       'Price'],
      dtype='object')

In [16]:
cat_cols

Index(['Location', 'Furnishing_Status', 'Parking_Available', 'Condition',
       'Has_Pool', 'Renovated'],
      dtype='object')

In [17]:
# Impute numerical columns with the mean
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

In [18]:
# Impute categorical columns with the mode
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

##Data Transfornation : One Hot Encoding

In [19]:
# Apply One-Hot Encoding to categorical columns
# drop_first=True helps avoid the dummy variable trap
df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [20]:
df_encoded.head()

,House_ID,Area_sqft,Bedrooms,Bathrooms,Floors,Year_Built,Garage_Count,Lot_Size_sqft,Distance_to_City_Center_km,Crime_Rate_Index,...,Has_Pool_No,Has_Pool_Y,Has_Pool_Yes,Has_Pool_no,Has_Pool_yes,Renovated_No,Renovated_Y,Renovated_Yes,Renovated_no,Renovated_yes
0,3975.0,1665.3,2.0,4.0,1.0,1988.0,3.0,4817.2,4.23,51.48,...,True,False,False,False,False,False,False,False,True,False
1,12325.0,2646.2,2.0,5.0,2.0,2005.0,3.0,6998.6,3.67,14.55,...,False,False,False,False,True,False,True,False,False,False
2,7202.0,2791.2,4.0,3.0,3.0,2011.0,0.0,3427.6,8.97,38.84,...,False,False,True,False,False,False,False,False,True,False
3,8355.0,1594.1,2.0,3.0,1.0,1972.0,3.0,5703.1,1.54,38.31,...,False,False,False,True,False,False,False,True,False,False
4,12742.0,3227.0,3.0,5.0,2.0,1995.0,3.0,7352.4,5.06,30.50,...,False,False,False,True,False,False,False,False,False,True

In [22]:
# Convert boolean values (True/False) to integers (1/0)
df_encoded = df_encoded.astype(int)
# Display the first few rows to verify the change
df_encoded.head()

,House_ID,Area_sqft,Bedrooms,Bathrooms,Floors,Year_Built,Garage_Count,Lot_Size_sqft,Distance_to_City_Center_km,Crime_Rate_Index,...,Has_Pool_No,Has_Pool_Y,Has_Pool_Yes,Has_Pool_no,Has_Pool_yes,Renovated_No,Renovated_Y,Renovated_Yes,Renovated_no,Renovated_yes
0,3975,1665,2,4,1,1988,3,4817,4,51,...,1,0,0,0,0,0,0,0,1,0
1,12325,2646,2,5,2,2005,3,6998,3,14,...,0,0,0,0,1,0,1,0,0,0
2,7202,2791,4,3,3,2011,0,3427,8,38,...,0,0,1,0,0,0,0,0,1,0
3,8355,1594,2,3,1,1972,3,5703,1,38,...,0,0,0,1,0,0,0,1,0,0
4,12742,3227,3,5,2,1995,3,7352,5,30,...,0,0,0,1,0,0,0,0,0,1

##Feature Scaling : Min-Max Normalization

In [23]:
X = df_encoded.drop('Price', axis=1)
y = df_encoded['Price']

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
# Initialize and apply Min-Max Scaler to the features
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [26]:
X_scaled.head()

,House_ID,Area_sqft,Bedrooms,Bathrooms,Floors,Year_Built,Garage_Count,Lot_Size_sqft,Distance_to_City_Center_km,Crime_Rate_Index,...,Has_Pool_No,Has_Pool_Y,Has_Pool_Yes,Has_Pool_no,Has_Pool_yes,Renovated_No,Renovated_Y,Renovated_Yes,Renovated_no,Renovated_yes
0,0.264951,0.301576,0.428571,0.030612,0.0,0.447059,1.0,0.335431,0.066667,0.51,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.821655,0.479261,0.428571,0.040816,0.5,0.647059,1.0,0.504895,0.050000,0.14,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.480099,0.505524,0.714286,0.020408,1.0,0.717647,0.0,0.227428,0.133333,0.38,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.556970,0.288716,0.428571,0.020408,0.0,0.258824,1.0,0.404274,0.016667,0.38,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.849457,0.584496,0.571429,0.040816,0.5,0.529412,1.0,0.532401,0.083333,0.30,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

##Train Test Split

In [27]:
from sklearn.model_selection import train_test_split

# Split data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

##Model Training

In [28]:
from sklearn.linear_model import LinearRegression

# Initialize the model
model = LinearRegression()

In [29]:
# Train the model on the training data
model.fit(X_train, y_train)

LinearRegression()

In [30]:
# Make predictions on the test set
y_pred = model.predict(X_test)

In [32]:
y_pred

array([310189.52684184, 353641.19053727, 389114.10163009, ...,
       356039.17143863, 328752.02767698, 447353.01568537])

##Regression Evaluation Metrics

In [34]:
# MAE, MSE, RMSE, R2 Score, Ajusted R2 Score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [35]:
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))

Mean Absolute Error (MAE): 29610.357809721805
Mean Squared Error (MSE): 1718986258.6572034

In [39]:
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R-squared (R2) Score:", r2_score(y_test, y_pred))

Root Mean Squared Error (RMSE): 41460.65916814641
R-squared (R2) Score: 0.8997156019445663